version: '3'

services:

  nodejs: 
    container_name: nodejs
    tty: true
    build:
      context: ./nodejs
      dockerfile: Dockerfile
    image: nodejs-fc
    networks:
      - node-nginx-app
    volumes:
      - ./nodejs/src:/usr/app/src
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    command: --innodb-use-native-aio=0    
    tty: true
    container_name: mysql
    restart: always
    networks:
      - node-nginx-app
    environment:
      - MYSQL_DATABASE=nodejs
      - MYSQL_USER=mysql.user
      - MYSQL_PASSWORD=mysql.password
      - MYSQL_ROOT_PASSWORD=mysql.root.password
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d

  nginx:
    container_name: nginx
    networks:
      - node-nginx-app
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx-fc
    ports:
      - 8080:80
    depends_on: 
      - nodejs

networks:
  node-nginx-app:
    name: node-nginx-app
    driver: bridge